[package]
authors = ["Olivier de Meringo <demeringo@gmail.com>"]
edition = "2021"
name = "scaph2cc"
version = "0.2.0"
[dependencies]
quick-junit = "0.1.5"
serde_json = "1.0.60"

[dependencies.clap]
features = ["derive"]
version = "3.1.6"

[dependencies.serde]
features = ["derive"]
version = "1.0"
